# Generated by Django 4.1 on 2022-09-06 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Audio', models.FileField(upload_to='../podcasts')),
                ('Summary', models.TextField()),
                ('Description', models.TextField()),
                ('Tag', models.CharField(max_length=30)),
            ],
        ),
    ]
