# Generated by Django 4.1 on 2022-09-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='Tag',
        ),
        migrations.AddField(
            model_name='podcast',
            name='Title',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
