# Generated by Django 4.1 on 2022-09-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0002_remove_podcast_tag_podcast_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podcast',
            old_name='Audio',
            new_name='upload',
        ),
        migrations.AlterField(
            model_name='podcast',
            name='Title',
            field=models.TextField(unique=True),
        ),
    ]
