# Generated by Django 4.1 on 2022-09-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0003_rename_audio_podcast_upload_alter_podcast_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='Title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
