# Generated by Django 4.1 on 2022-09-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0008_alter_podcast_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='Delete',
            field=models.BooleanField(default=False),
        ),
    ]
