# Generated by Django 4.1 on 2022-09-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0009_podcast_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='Title',
            field=models.CharField(max_length=100),
        ),
    ]
